In [1]:
import numpy as np
import math

In [15]:
x = [[0, 1], [1, 0]]
h = [[0.70710678, 0.70710678], [0.70710678, -0.70710678]]
cx = np.empty(2)
# Define projection operator |0><0|
P0x0 = np.array([
[1, 0],
[0, 0]
])

# Define projection operator |1><1|
P1x1 = np.array([
[0, 0],
[0, 1]
])

In [123]:
def get_ground_state(num_qubits):
    # return vector of size 2**num_qubits with all zeroes except first element which is 1
    v = []
    for i in range(2**num_qubits):
        if i == 0:
            v.append(1)
        else:
            v.append(0)
    return v

def get_operator(total_qubits, gate_unitary, target_qubits):
    # return unitary operator of size 2**n x 2**n for given gate and target qubits
    
    '''#Code for single qubit gates
    I = np.identity(2)
    flag = 0
    
    if target_qubits[0] == 0:
        O = np.kron(gate_unitary, I)
        flag = 1
    elif target_qubits[0] == 1:
        O = np.kron(I, gate_unitary)
        flag = 1
    
    for i in range((total_qubits - 1) - flag):
        if flag == 1:
            O = np.kron(O, I)
        elif i == (target_qubits[0] - 1):
            O = np.kron(O, gate_unitary)
        elif i == 0:
            O = np.kron(I, I)
        else:
            O = np.kron(O, I)'''       
    
    #Code for multi-qubit gate cx
    I = np.identity(2)
    flag1 = 0
    flag2 = 0
    
    #Works for gate after projection PU or PI
    if target_qubits[0] == 0:
        if target_qubits[1] == 1:
            first_term = np.kron(P0x0, I)
            second_term = np.kron(P1x1, gate_unitary)
            flag2 = 1
        else:
            first_term = np.kron(P0x0, I)
            second_term = np.kron(P1x1, I)
        flag1 = 1
    elif target_qubits[0] == 1:
        if target_qubits[1] == 0:
            first_term = np.kron(I, P0x0)
            second_term = np.kron(gate_unitary, P1x1)
            flag2 = 1
        else:
            first_term = np.kron(I, P0x0)
            second_term = np.kron(I, P1x1)
        flag1 = 1
    
    '''#For projection after gate UP or UI
    if target_qubits[1] == 0:
        if target_qubits[0] == 1:
            first_term = np.kron(I, P1x1)
            second_term = np.kron(gate_unitary, P1x1)
            flag1 = 1
        else:
            first_term = np.kron(I, I)
            second_term = np.kron(gate_unitary, I)
        flag2 = 1
    elif target_qubits[1] == 1:
        if target_qubits[0] == 0:
            first_term = np.kron(P0x0, I)
            second_term = np.kron(P1x1, gate_unitary)
            flag1 = 1
        else:
            first_term = np.kron(P0x0, I)
            second_term = np.kron(gate_unitary, I)
        flag2 = 1'''
    
    for i in range((total_qubits - 1) - flag1):
        if flag1 == 1 and flag2 == 1:
            first_term = np.kron(first_term, I)
            second_term = np.kron(second_term, I)
            
        elif flag1 == 0 and i == (target_qubits[0] - 1):
            first_term = np.kron(first_term, P0x0)
            second_term = np.kron(second_term, P1x1)
            flag1 = 1
            
        elif flag2 == 0 and i == (target_qubits[1] - 2):
            first_term = np.kron(first_term, I)
            second_term = np.kron(second_term, gate_unitary)
            flag2 = 1
            
        '''elif flag1 == 0 and i == (target_qubits[1] - 1):
            first_term = np.kron(first_term, I)
            second_term = np.kron(second_term, gate_unitary)
            flag2 = 1
            
        elif flag2 == 0 and i == (target_qubits[0] - 2):
            first_term = np.kron(first_term, P0x0)
            second_term = np.kron(second_term, P1x1)
            flag1 = 1'''
        
        elif (flag1 == 0 and flag2 == 0) and i == 0:
            first_term = np.kron(I, I)
            second_term = np.kron(I, I)
        else:
            first_term = np.kron(first_term, I)
            second_term = np.kron(second_term, I)
    
    O = first_term + second_term
    
    return O

def run_program(initial_state, program):
    # read program, and for each gate:
    #   - calculate matrix operator
    #   - multiply state with operator
    # return final state
    O = get_operator(int(math.log(len(my_qpu))/math.log(2)), program[0]["gate"], program[0]["target"])
    print(O)
    final_state = np.dot(initial_state, O)
    return final_state

SyntaxError: invalid syntax (<ipython-input-123-4ce226ffcb49>, line 105)

In [127]:
# Create "quantum computer" with 2 qubits (this is actually just a vector :) )
my_qpu = [0, 0, 0, 0, 0, 1, 0, 0]

my_qpu

[0, 0, 0, 0, 0, 1, 0, 0]

In [128]:
my_circuit = [
{ "gate": x, "target": [0, 2] }
]
print(my_circuit[0]["gate"])

[[0, 1], [1, 0]]


In [129]:
# Run circuit

final_state = run_program(my_qpu, my_circuit)
print(" ")
print("Final State: ",final_state)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]
 
Final State:  [0. 0. 0. 0. 1. 0. 0. 0.]
